### ISSUE TITLE
Looking for a docker that can run on sm_80 GPU

### ISSUE THREAD

**Issue by Xiao9905** [laituan245/EL-Dockers#1]
Hi @laituan245 ,

Thanks for your great work! It's really helpful for me. I am using 3090 GPU but find your docker `laituan245/wikidata_el_demo` can not support it. It seems that the torch version in docker is lower than 1.11.

Could you please provide a docker that satisfy the condition? Many thanks.

**Comment by laituan245** [comment]
Could you describe about the issue in more details? For example, if there was an error, could you post the error message?

Since the system is encapsulated in a docker, I guess it doesn't really matter what is the torch version used inside the docker.

**Comment by Xiao9905** [comment]
Here's the error:
```
/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/cuda/__init__.py:143: UserWarning:
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "linking_demo.py", line 17, in <module>
    nlp = stanza.Pipeline(lang='en', processors='tokenize')
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/core.py", line 143, in __init__
    use_gpu=self.use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/processor.py", line 159, in __init__
    self._set_up_model(config, use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/tokenize_processor.py", line 40, in _set_up_model
    self._trainer = Trainer(model_file=config['model_path'], use_cuda=use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/models/tokenization/trainer.py", line 30, in __init__
    self.model.cuda()
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 680, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 680, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
CRITICAL: Exiting due to uncaught exception <class 'RuntimeError'>
```

**Comment by Xiao9905** [comment]
Here's the error:

```
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Passed test cases for utils/basic.py
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Traceback (most recent call last):
  File "linking_demo.py", line 17, in <module>
    nlp = stanza.Pipeline(lang='en', processors='tokenize')
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/core.py", line 143, in __init__
    use_gpu=self.use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/processor.py", line 159, in __init__
    self._set_up_model(config, use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/pipeline/tokenize_processor.py", line 40, in _set_up_model
    self._trainer = Trainer(model_file=config['model_path'], use_cuda=use_gpu)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/stanza/models/tokenization/trainer.py", line 30, in __init__
    self.model.cuda()
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 680, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 189, in _apply
    self.flatten_parameters()
  File "/opt/conda/envs/aida_coreference/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 179, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
CRITICAL: Exiting due to uncaught exception <class 'RuntimeError'>
```
I have encountered such errors and solve by reinstall torch and cudatoolkit with `conda install torch torchvision cudatoolkit -c pytorch` on sm_86 based GPU.

**Comment by laituan245** [comment]
Thanks. I will look into this during this weekend. It may take a little time since I don't have access to RTX 3090 to test at the moment.

**Comment by Xiao9905** [comment]
Thanks! Looking forward to your reply.

**Comment by laituan245** [comment]
I created a new docker `laituan245/wikidata_el_demo:cu11` with updated cuda version and pytorch. Could you try again?

Basically, the command format should now be

`docker run --net=host --gpus '"device=0"' --rm -v /shared:/shared laituan245/wikidata_el_demo:cu11 --input_fp test_inputs.jsonl --output_fp test_outputs.jsonl`

**Comment by Xiao9905** [comment]
Thanks! I'll have a quick try today.
